=== mycurelabs/philhealth-documentation/docs/public/originals/data-migration/eClaimsXmlForDataMigration.dtd
<!--
    Philippine Health Insurance Corporation
    eClaims for Migration Document Type Definition Version 1.0
    Version History
    1.0.0.0 2024-11-25 06:43PM
      - Initial Release
    1.0.0.1 2024-12-10 04:44PM
      - Added the closing parenthesis in the declaration of the CLAIM element    
      - Added "+" after OFFLINEDOCUMENT in the declaration of the 
        OFFLINEDOCUMENTS element to specify that there should be at leasy
        on OFFLINEDOCUMENT element if OFFLINEDOCUMENTS element exist    
      - Added the (#PCDATA) in the the declaration of the OFFLINEDOCUMENT element  
-->

<!ENTITY Ntilde "&#209;">
<!ENTITY ntilde "&#241;">
<!ENTITY nbsp "&#160;">

<!ELEMENT eCLAIMS (eTRANSMITTAL)>
<!ATTLIST eCLAIMS
    pUserName CDATA #REQUIRED
    pUserPassword CDATA #REQUIRED
    pHospitalCode CDATA #REQUIRED
    pHospitalEmail CDATA #REQUIRED
    pServiceProvider CDATA #IMPLIED>

<!ELEMENT eTRANSMITTAL (CLAIM+)>
<!ATTLIST eTRANSMITTAL
    pHospitalTransmittalNo CDATA #REQUIRED
    pTotalClaims CDATA #REQUIRED>

<!ELEMENT CLAIM (CF1, CF2, (ALLCASERATE | ZBENEFIT), CF3?, PARTICULARS?, RECEIPTS?, OFFLINEDOCUMENTS?)>
<!ATTLIST CLAIM
    pClaimNumber CDATA #REQUIRED
    pTrackingNumber CDATA #REQUIRED
    pPhilhealthClaimType (ALL-CASE-RATE|Z-BENEFIT) #REQUIRED
    pPatientType (I|O) #REQUIRED
    pIsEmergency (Y|N) #REQUIRED
    pClaimSeriesLhio CDATA #REQUIRED>

<!ELEMENT CF1 EMPTY>
<!ATTLIST CF1
    pMemberPIN CDATA #REQUIRED
    pMemberLastName CDATA #REQUIRED
    pMemberFirstName CDATA #REQUIRED
    pMemberSuffix CDATA #REQUIRED
    pMemberMiddleName CDATA #REQUIRED
    pMemberBirthDate CDATA #REQUIRED
    pMemberShipType (S|G|I|NS|NO|PS|PG|P) #REQUIRED
    pMailingAddress CDATA #REQUIRED
    pZipCode CDATA #REQUIRED
    pMemberSex (M|F) #REQUIRED
    pLandlineNo CDATA #REQUIRED
    pMobileNo CDATA #REQUIRED
    pEmailAddress CDATA #REQUIRED
    pPatientIs (M|S|C|P) #REQUIRED
    pPatientPIN CDATA #REQUIRED
    pPatientLastName CDATA #REQUIRED
    pPatientFirstName CDATA #REQUIRED
    pPatientSuffix CDATA #REQUIRED
    pPatientMiddleName CDATA #REQUIRED
    pPatientBirthDate CDATA #REQUIRED
    pPatientSex (M|F) #REQUIRED
    pPEN CDATA #REQUIRED
    pEmployerName CDATA #REQUIRED>

<!ELEMENT CF2 (DIAGNOSIS, SPECIAL, PROFESSIONALS+, CONSUMPTION, APR?)>
<!ATTLIST CF2
    pPatientReferred (Y|N) #REQUIRED
    pReferredIHCPAccreCode CDATA #REQUIRED
    pAdmissionDate CDATA #REQUIRED
    pAdmissionTime CDATA #REQUIRED
    pDischargeDate CDATA #REQUIRED
    pDischargeTime CDATA #REQUIRED
    pDisposition (I|R|H|A|E|T) #REQUIRED
    pExpiredDate CDATA #REQUIRED
    pExpiredTime CDATA #REQUIRED
    pReferralIHCPAccreCode CDATA #REQUIRED
    pReferralReasons CDATA #REQUIRED
    pAccommodationType (P|N) #REQUIRED
    pHasAttachedSOA (Y|N) #IMPLIED>

<!ELEMENT DIAGNOSIS (DISCHARGE+)>
<!ATTLIST DIAGNOSIS
    pAdmissionDiagnosis CDATA #REQUIRED>

<!ELEMENT DISCHARGE ((ICDCODE+, RVSCODES*)|(ICDCODE*, RVSCODES+))>
<!ATTLIST DISCHARGE
    pDischargeDiagnosis CDATA #REQUIRED>

<!ELEMENT ICDCODE EMPTY>
<!ATTLIST ICDCODE
    pICDCode CDATA #REQUIRED>

<!ELEMENT RVSCODES EMPTY>
<!ATTLIST RVSCODES
    pRelatedProcedure CDATA #REQUIRED
    pRVSCode CDATA #REQUIRED
    pProcedureDate CDATA #REQUIRED
    pLaterality (L|R|B|N) #REQUIRED>

<!ELEMENT SPECIAL (PROCEDURES?, MCP?, TBDOTS?, ABP?, NCP?, HIVAIDS?, CATARACTINFO?)>

<!ELEMENT PROCEDURES ((HEMODIALYSIS?, PERITONEAL?, LINAC?, COBALT?, TRANSFUSION?, BRACHYTHERAPHY?, CHEMOTHERAPY?, DEBRIDEMENT?, IMRT?), (HEMODIALYSIS|PERITONEAL|LINAC|COBALT|TRANSFUSION|BRACHYTHERAPHY|CHEMOTHERAPY|DEBRIDEMENT|IMRT))>
<!ELEMENT HEMODIALYSIS (SESSIONS*)>
<!ELEMENT PERITONEAL (SESSIONS*)>
<!ELEMENT LINAC (SESSIONS*)>
<!ELEMENT COBALT (SESSIONS*)>
<!ELEMENT TRANSFUSION (SESSIONS*)>
<!ELEMENT BRACHYTHERAPHY (SESSIONS*)>
<!ELEMENT CHEMOTHERAPY (SESSIONS*)>
<!ELEMENT DEBRIDEMENT (SESSIONS*)>
<!ELEMENT IMRT (SESSIONS*)>

<!ELEMENT SESSIONS EMPTY>
<!ATTLIST SESSIONS
    pSessionDate CDATA #REQUIRED>

<!ELEMENT MCP EMPTY>
<!ATTLIST MCP
    pCheckUpDate1 CDATA #REQUIRED
    pCheckUpDate2 CDATA #REQUIRED
    pCheckUpDate3 CDATA #REQUIRED
    pCheckUpDate4 CDATA #REQUIRED>

<!ELEMENT TBDOTS EMPTY>
<!ATTLIST TBDOTS
    pTBType (I|M) #REQUIRED
    pNTPCardNo CDATA #REQUIRED>

<!ELEMENT ABP EMPTY>
<!ATTLIST ABP
    pDay0ARV CDATA #REQUIRED
    pDay3ARV CDATA #REQUIRED
    pDay7ARV CDATA #REQUIRED
    pRIG CDATA #REQUIRED
    pABPOthers CDATA #REQUIRED
    pABPSpecify CDATA #REQUIRED>

<!ELEMENT NCP (ESSENTIAL?)>
<!ATTLIST NCP
    pEssentialNewbornCare (Y|N) #REQUIRED
    pNewbornHearingScreeningTest (Y|N) #REQUIRED
    pNewbornScreeningTest (Y|N) #REQUIRED
    pFilterCardNo CDATA #REQUIRED
    pNewbornHearingRegistryNo CDATA #REQUIRED
    pNewbornHearingScreeningTestResult (P|R|X) #REQUIRED>

<!ELEMENT ESSENTIAL EMPTY>
<!ATTLIST ESSENTIAL
    pDrying (Y|N) #REQUIRED
    pSkinToSkin (Y|N) #REQUIRED
    pCordClamping (Y|N) #REQUIRED
    pProphylaxis (Y|N) #REQUIRED
    pWeighing (Y|N) #REQUIRED
    pVitaminK (Y|N) #REQUIRED
    pBCG (Y|N) #REQUIRED
    pNonSeparation (Y|N) #REQUIRED
    pHepatitisB (Y|N) #REQUIRED>

<!ELEMENT HIVAIDS EMPTY>
<!ATTLIST HIVAIDS
    pLaboratoryNumber CDATA #REQUIRED>

<!ELEMENT CATARACTINFO EMPTY>
<!ATTLIST CATARACTINFO
    pCataractPreAuth CDATA #REQUIRED
        pLeftEyeIOLStickerNumber CDATA #REQUIRED
        pLeftEyeIOLExpiryDate CDATA #REQUIRED
        pRightEyeIOLStickerNumber CDATA #REQUIRED
        pRightEyeIOLExpiryDate CDATA #REQUIRED>

<!ELEMENT PROFESSIONALS EMPTY>
<!ATTLIST PROFESSIONALS
    pDoctorAccreCode CDATA #REQUIRED
    pDoctorLastName CDATA #REQUIRED
    pDoctorFirstName CDATA #REQUIRED
    pDoctorMiddleName CDATA #REQUIRED
    pDoctorSuffix CDATA #REQUIRED
    pWithCoPay (Y|N) #REQUIRED
    pDoctorCoPay CDATA #REQUIRED
    pDoctorSignDate CDATA #REQUIRED>

<!ELEMENT CONSUMPTION (BENEFITS|(HCIFEES, PROFFEES, PURCHASES))>
<!ATTLIST CONSUMPTION
    pEnoughBenefits (Y|N) #REQUIRED>

<!ELEMENT APR (APRBYPATSIG|APRBYPATREPSIG|APRBYTHUMBMARK)>

<!ELEMENT APRBYPATSIG EMPTY>
<!ATTLIST APRBYPATSIG
    pDateSigned CDATA #REQUIRED>

<!ELEMENT APRBYPATREPSIG ((DEFINEDPATREPREL|OTHERPATREPREL), (DEFINEDREASONFORSIGNING|OTHERREASONFORSIGNING))>
<!ATTLIST APRBYPATREPSIG 
    pDateSigned CDATA #REQUIRED>

<!ELEMENT DEFINEDPATREPREL EMPTY>
<!--    pRelCode: One of
			S: Spouse
			C: Child
			P: Parent
			I: Siblings
			O: Others-->
<!ATTLIST DEFINEDPATREPREL
    pRelCode (S|C|P|I) #REQUIRED> 
<!ELEMENT OTHERPATREPREL EMPTY>
<!ATTLIST OTHERPATREPREL
        pRelCode CDATA #FIXED "O"
    pRelDesc CDATA #REQUIRED> 

<!ELEMENT DEFINEDREASONFORSIGNING EMPTY>
<!-- pReasonCode:    One of
    I: Patient is incapacitated
    O: Other reasons. Should be specified in pReasonDesc
    -->
<!ATTLIST DEFINEDREASONFORSIGNING
        pReasonCode (I) #REQUIRED> 
<!ELEMENT OTHERREASONFORSIGNING EMPTY>
<!ATTLIST OTHERREASONFORSIGNING
        pReasonCode CDATA #FIXED "O"
    pReasonDesc CDATA #REQUIRED> 


<!ELEMENT APRBYTHUMBMARK EMPTY>
<!--pThumbmarkedBy:    One of
        P: by patient/member
        R: by representative
    -->
<!ATTLIST APRBYTHUMBMARK
    pThumbmarkedBy (P|R) #REQUIRED>
    
<!ELEMENT BENEFITS EMPTY>
<!ATTLIST BENEFITS
    pTotalHCIFees CDATA #REQUIRED
    pTotalProfFees CDATA #REQUIRED
    pGrandTotal CDATA #REQUIRED>
    
<!ELEMENT HCIFEES EMPTY>
<!ATTLIST HCIFEES
    pTotalActualCharges CDATA #REQUIRED
    pDiscount CDATA #REQUIRED
    pPhilhealthBenefit CDATA #REQUIRED
    pTotalAmount CDATA #REQUIRED
    pMemberPatient (Y|N) #REQUIRED
    pHMO (Y|N) #REQUIRED
    pOthers (Y|N) #REQUIRED>    
    
<!ELEMENT PROFFEES EMPTY>
<!ATTLIST PROFFEES
    pTotalActualCharges CDATA #REQUIRED
    pDiscount CDATA #REQUIRED
    pPhilhealthBenefit CDATA #REQUIRED
    pTotalAmount CDATA #REQUIRED
    pMemberPatient (Y|N) #REQUIRED
    pHMO (Y|N) #REQUIRED
    pOthers (Y|N) #REQUIRED>
    
<!ELEMENT PURCHASES EMPTY>
<!ATTLIST PURCHASES
    pDrugsMedicinesSupplies (Y|N) #REQUIRED
    pDMSTotalAmount CDATA #REQUIRED
    pExaminations (Y|N) #REQUIRED
    pExamTotalAmount CDATA #REQUIRED>   

<!ELEMENT ALLCASERATE (CASERATE+)>
<!ELEMENT CASERATE (CATARACT?)>
<!ATTLIST CASERATE
    pCaseRateCode CDATA #REQUIRED
    pICDCode CDATA #REQUIRED
    pRVSCode CDATA #REQUIRED
    pCaseRateAmount CDATA #REQUIRED>
    
<!ELEMENT CATARACT EMPTY>
<!ATTLIST CATARACT
    pCataractPreAuth CDATA #REQUIRED>

<!ELEMENT ZBENEFIT EMPTY>
<!ATTLIST ZBENEFIT
    pZBenefitCode (Z0011|Z0012|Z0013|Z0021|Z0022|Z003|Z0041|Z0042|Z0051|Z0052|Z0061|Z0062|Z0071|Z0072|Z0081|Z0082|Z0091|Z0092) #REQUIRED
    pPreAuthDate CDATA #REQUIRED>

<!ELEMENT CF3 (CF3_OLD?, CF3_NEW?)>
<!ELEMENT CF3_OLD (PHEX, MATERNITY?)>
<!ATTLIST CF3_OLD
    pChiefComplaint CDATA #REQUIRED
    pBriefHistory CDATA #REQUIRED
    pCourseWard CDATA #REQUIRED
    pPertinentFindings CDATA #REQUIRED>
    
<!ELEMENT MATERNITY (PRENATAL, DELIVERY, POSTPARTUM)>   
<!ELEMENT PRENATAL (CLINICALHIST, OBSTETRIC, MEDISURG, CONSULTATION+)>
<!ATTLIST PRENATAL
    pPrenatalConsultation CDATA #REQUIRED
    pMCPOrientation (Y|N) #REQUIRED
    pExpectedDeliveryDate CDATA #REQUIRED>
    
<!ELEMENT CLINICALHIST EMPTY>
<!ATTLIST CLINICALHIST
    pVitalSigns (Y|N) #REQUIRED
    pPregnancyLowRisk (Y|N) #REQUIRED
    pLMP CDATA #REQUIRED
    pMenarcheAge CDATA #REQUIRED
    pObstetricG CDATA #REQUIRED
    pObstetricP CDATA #REQUIRED
    pObstetric_T CDATA #REQUIRED
    pObstetric_P CDATA #REQUIRED
    pObstetric_A CDATA #REQUIRED
    pObstetric_L CDATA #REQUIRED>
    
<!ELEMENT OBSTETRIC EMPTY>
<!ATTLIST OBSTETRIC
    pMultiplePregnancy (Y|N) #REQUIRED
    pOvarianCyst (Y|N) #REQUIRED
    pMyomaUteri (Y|N) #REQUIRED
    pPlacentaPrevia (Y|N) #REQUIRED
    pMiscarriages (Y|N) #REQUIRED
    pStillBirth (Y|N) #REQUIRED
    pPreEclampsia (Y|N) #REQUIRED
    pEclampsia (Y|N) #REQUIRED
    pPrematureContraction (Y|N) #REQUIRED>
    
<!ELEMENT MEDISURG EMPTY>
<!ATTLIST MEDISURG
    pHypertension (Y|N) #REQUIRED
    pHeartDisease (Y|N) #REQUIRED
    pDiabetes (Y|N) #REQUIRED
    pThyroidDisaster (Y|N) #REQUIRED
    pObesity (Y|N) #REQUIRED
    pAsthma (Y|N) #REQUIRED
    pEpilepsy (Y|N) #REQUIRED
    pRenalDisease (Y|N) #REQUIRED
    pBleedingDisorders (Y|N) #REQUIRED
    pPreviousCS (Y|N) #REQUIRED
    pUterineMyomectomy (Y|N) #REQUIRED>
    
<!ELEMENT CONSULTATION EMPTY>
<!ATTLIST CONSULTATION
    pVisitDate CDATA #REQUIRED
    pAOGWeeks CDATA #REQUIRED
    pWeight CDATA #REQUIRED
    pCardiacRate CDATA #REQUIRED
    pRespiratoryRate CDATA #REQUIRED
    pBloodPressure CDATA #REQUIRED
    pTemperature CDATA #REQUIRED>   
    
<!ELEMENT DELIVERY EMPTY>
<!ATTLIST DELIVERY
    pDeliveryDate CDATA #REQUIRED
    pDeliveryTime CDATA #REQUIRED
    pObstetricIndex CDATA #REQUIRED
    pAOGLMP CDATA #REQUIRED
    pDeliveryManner CDATA #REQUIRED
    pPresentation CDATA #REQUIRED
    pFetalOutcome CDATA #REQUIRED
    pSex CDATA #REQUIRED
    pBirthWeight CDATA #REQUIRED
    pAPGARScore CDATA #REQUIRED
    pPostpartum CDATA #REQUIRED>    
    
<!ELEMENT POSTPARTUM EMPTY>
<!ATTLIST POSTPARTUM
    pPerinealWoundCare (Y|N) #REQUIRED
    pPerinealRemarks CDATA #REQUIRED
    pMaternalComplications (Y|N) #REQUIRED
    pMaternalRemarks CDATA #REQUIRED
    pBreastFeeding (Y|N) #REQUIRED
    pBreastFeedingRemarks CDATA #REQUIRED
    pFamilyPlanning (Y|N) #REQUIRED
    pFamilyPlanningRemarks CDATA #REQUIRED
    pPlanningService (Y|N) #REQUIRED
    pPlanningServiceRemarks CDATA #REQUIRED
    pSurgicalSterilization (Y|N) #REQUIRED
    pSterilizationRemarks CDATA #REQUIRED
    pFollowupSchedule (Y|N) #REQUIRED
    pFollowupScheduleRemarks CDATA #REQUIRED>           

<!ELEMENT CF3_NEW (ADMITREASON?, COURSE?)>

<!ELEMENT ADMITREASON (CLINICAL+, LABDIAG+, PHEX)>
<!ATTLIST ADMITREASON
    pBriefHistory CDATA #REQUIRED
    pReferredReason CDATA #REQUIRED
    pIntensive (Y|N) #REQUIRED
    pMaintenance (Y|N) #REQUIRED>

<!ELEMENT CLINICAL EMPTY>
<!ATTLIST CLINICAL
    pCriteria CDATA #REQUIRED>

<!ELEMENT LABDIAG EMPTY>
<!ATTLIST LABDIAG
    pCriteria CDATA #REQUIRED>

<!ELEMENT PHEX EMPTY>
<!ATTLIST PHEX
    pBP CDATA #REQUIRED
    pCR CDATA #REQUIRED
    pRR CDATA #REQUIRED
    pTemp CDATA #REQUIRED
    pHEENT CDATA #REQUIRED
    pChestLungs CDATA #REQUIRED
    pCVS CDATA #REQUIRED
    pAbdomen CDATA #REQUIRED
    pGUIE CDATA #REQUIRED
    pSkinExtremities CDATA #REQUIRED
    pNeuroExam CDATA #REQUIRED>

<!ELEMENT COURSE (WARD+)>
<!ELEMENT WARD EMPTY>
<!ATTLIST WARD
    pCourseDate CDATA #REQUIRED
    pFindings CDATA #REQUIRED
    pAction CDATA #REQUIRED>    

<!ELEMENT PARTICULARS ((DRGMED+|XLSO+), (DRGMED*|XLSO*))>
<!ELEMENT DRGMED EMPTY>
<!ATTLIST DRGMED
    pPurchaseDate CDATA #REQUIRED
    pDrugCode CDATA #REQUIRED
    pPNDFCode CDATA #REQUIRED
    pGenericName CDATA #REQUIRED
    pBrandName CDATA #REQUIRED
    pPreparation CDATA #REQUIRED
    pQuantity CDATA #REQUIRED>
<!ELEMENT XLSO EMPTY>
<!ATTLIST XLSO
    pDiagnosticDate CDATA #REQUIRED
    pDiagnosticType (IMAGING|LABORATORY|SUPPLIES|OTHERS) #REQUIRED
    pDiagnosticName CDATA #REQUIRED
    pQuantity CDATA #REQUIRED>

<!ELEMENT RECEIPTS (RECEIPT+)>
<!ELEMENT RECEIPT (ITEM+)>
<!ATTLIST RECEIPT
    pCompanyName CDATA #REQUIRED
    pCompanyTIN CDATA #REQUIRED
    pBIRPermitNumber CDATA #REQUIRED
    pReceiptNumber CDATA #REQUIRED
    pReceiptDate CDATA #REQUIRED
    pVATExemptSale CDATA #REQUIRED
    pVAT CDATA #REQUIRED
    pTotal CDATA #REQUIRED>
<!ELEMENT ITEM EMPTY>
<!ATTLIST ITEM
    pQuantity CDATA #REQUIRED
    pUnitPrice CDATA #REQUIRED
    pDescription CDATA #REQUIRED
    pAmount CDATA #REQUIRED>


<!ELEMENT OFFLINEDOCUMENTS (OFFLINEDOCUMENT+)>
<!ELEMENT OFFLINEDOCUMENT (#PCDATA)>
<!ATTLIST OFFLINEDOCUMENT
	pDocumentType CDATA #REQUIRED
	pMimeType CDATA #REQUIRED
	pEncryptionUsed (N|C|P) #REQUIRED>

=== mycurelabs/philhealth-documentation/docs/public/examples/migration-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eCLAIMS SYSTEM "eClaimsXmlForDataMigration.dtd">
<!--
  UNOFFICIAL example of an e-Claims XML file for data migration.
  Written for this documentation site; it is not a PhilHealth sample.

  Validity: checked against eClaimsXmlForDataMigration.dtd (v1.0.0.1,
  2024-12-10) with Java's validating parser (JAXP) and with lxml against a
  patched copy of the DTD. A plain libxml2 check (lxml, xmllint, PHP) fails
  on the DTD itself, not on this file. See /known-issues#ki-43.

  Values: the site's shared sample scenario (the same claim as
  /examples/eclaims-minimal.xml). They are placeholders, not real data.
  - PIN 072007271094 and the member's name and birth date are the
    Implementation Guide's sample values (p. 29). No test member exists.
  - Doctor 1504-2400015-3 (LIFE GOES ON) and employer 110474000002
    (JOSE A TERAMOTO ODM) come from "Dummy Health Care Providers and
    Employers.pdf".
  - pClaimSeriesLhio 260917990000101 is an illustrative value. A real one
    comes from getUploadedClaimsMap.
  - pEncryptionUsed="N" assumes that N means "not encrypted". The DevKit
    defines N, C and P nowhere. See /known-issues#ki-54.

  Before handing this file to another provider, encrypt the WHOLE file with
  the health facility's cipher key (Annex A procedure).
-->
<eCLAIMS
    pUserName=":SAMPLE-CERT-ID"
    pUserPassword=""
    pHospitalCode="123456"
    pHospitalEmail="eclaims@samplehospital.example"
    pServiceProvider="SAMPLE HIS">
  <eTRANSMITTAL
      pHospitalTransmittalNo="TR20260917001"
      pTotalClaims="1">
    <CLAIM
        pClaimNumber="202609170001"
        pTrackingNumber=""
        pPhilhealthClaimType="ALL-CASE-RATE"
        pPatientType="I"
        pIsEmergency="N"
        pClaimSeriesLhio="260917990000101">
      <CF1
          pMemberPIN="072007271094"
          pMemberLastName="DELA CRUZ"
          pMemberFirstName="JUAN"
          pMemberSuffix=""
          pMemberMiddleName="OCAMPO"
          pMemberBirthDate="09-19-1973"
          pMemberShipType="S"
          pMailingAddress="123 SAMPLE STREET, BARANGAY UNO, QUEZON CITY"
          pZipCode="1100"
          pMemberSex="M"
          pLandlineNo=""
          pMobileNo=""
          pEmailAddress=""
          pPatientIs="M"
          pPatientPIN="072007271094"
          pPatientLastName="DELA CRUZ"
          pPatientFirstName="JUAN"
          pPatientSuffix=""
          pPatientMiddleName="OCAMPO"
          pPatientBirthDate="09-19-1973"
          pPatientSex="M"
          pPEN="110474000002"
          pEmployerName="JOSE A TERAMOTO ODM"/>
      <CF2
          pPatientReferred="N"
          pReferredIHCPAccreCode=""
          pAdmissionDate="09-15-2026"
          pAdmissionTime="01:00:00PM"
          pDischargeDate="09-17-2026"
          pDischargeTime="03:00:00PM"
          pDisposition="I"
          pExpiredDate=""
          pExpiredTime=""
          pReferralIHCPAccreCode=""
          pReferralReasons=""
          pAccommodationType="N"
          pHasAttachedSOA="Y">
        <DIAGNOSIS pAdmissionDiagnosis="DENGUE FEVER">
          <DISCHARGE pDischargeDiagnosis="DENGUE FEVER WITHOUT WARNING SIGNS">
            <ICDCODE pICDCode="A90"/>
          </DISCHARGE>
        </DIAGNOSIS>
        <!-- SPECIAL is required by the DTD even when it is empty.
             A newborn claim would carry NCP here, and in this format NCP also
             requires pNewbornHearingRegistryNo and
             pNewbornHearingScreeningTestResult (P, R or X; undefined, see
             /known-issues#ki-10). Repetitive procedures use repeated
             SESSIONS elements; there is no SESSION element (/known-issues#ki-37). -->
        <SPECIAL/>
        <PROFESSIONALS
            pDoctorAccreCode="1504-2400015-3"
            pDoctorLastName="ON"
            pDoctorFirstName="LIFE"
            pDoctorMiddleName="GOES"
            pDoctorSuffix=""
            pWithCoPay="N"
            pDoctorCoPay=""
            pDoctorSignDate="09-17-2026"/>
        <CONSUMPTION pEnoughBenefits="Y">
          <BENEFITS
              pTotalHCIFees="7000.00"
              pTotalProfFees="3000.00"
              pGrandTotal="10000.00"/>
        </CONSUMPTION>
        <APR>
          <APRBYPATSIG pDateSigned="09-17-2026"/>
        </APR>
      </CF2>
      <ALLCASERATE>
        <CASERATE
            pCaseRateCode="CR0001"
            pICDCode="A90"
            pRVSCode=""
            pCaseRateAmount="10000.00"/>
      </ALLCASERATE>
      <!-- Supporting documents travel INSIDE the file as base64 text,
           instead of DOCUMENT/@pDocumentURL links. A real export embeds every
           document of the claim; to stay short, this example embeds only the
           CSF and the CF5 (the uploaded claim also had ESA and CF4). -->
      <OFFLINEDOCUMENTS>
        <!-- A 594-byte placeholder PDF whose only text is "SAMPLE CSF - NOT REAL". -->
        <OFFLINEDOCUMENT pDocumentType="CSF" pMimeType="application/pdf" pEncryptionUsed="N">JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCAyMDAgNjBdIC9Db250ZW50cyA0IDAgUiAvUmVzb3VyY2VzIDw8IC9Gb250IDw8IC9GMSA1IDAgUiA+PiA+PiA+PgplbmRvYmoKNCAwIG9iago8PCAvTGVuZ3RoIDUxID4+CnN0cmVhbQpCVCAvRjEgMTAgVGYgMTAgMjUgVGQgKFNBTVBMRSBDU0YgLSBOT1QgUkVBTCkgVGogRVQKZW5kc3RyZWFtCmVuZG9iago1IDAgb2JqCjw8IC9UeXBlIC9Gb250IC9TdWJ0eXBlIC9UeXBlMSAvQmFzZUZvbnQgL0hlbHZldGljYSA+PgplbmRvYmoKeHJlZgowIDYKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDA5IDAwMDAwIG4gCjAwMDAwMDAwNTggMDAwMDAgbiAKMDAwMDAwMDExNSAwMDAwMCBuIAowMDAwMDAwMjQwIDAwMDAwIG4gCjAwMDAwMDAzNDEgMDAwMDAgbiAKdHJhaWxlcgo8PCAvU2l6ZSA2IC9Sb290IDEgMCBSID4+CnN0YXJ0eHJlZgo0MTEKJSVFT0YK</OFFLINEDOCUMENT>
        <!-- A 161-byte CF5 XML (valid against cf5/CF5.dtd): pHospitalCode 123456,
             ClaimNumber 202609170001 (the same value as CLAIM@pClaimNumber,
             see /known-issues#ki-45), PrimaryCode A90. -->
        <OFFLINEDOCUMENT pDocumentType="CF5" pMimeType="application/xml" pEncryptionUsed="N">PENGNSBwSG9zcGl0YWxDb2RlPSIxMjM0NTYiPjxEUkdDTEFJTSBDbGFpbU51bWJlcj0iMjAyNjA5MTcwMDAxIiBQcmltYXJ5Q29kZT0iQTkwIiBOZXdCb3JuQWRtV2VpZ2h0PSIiIFJlbWFya3M9IiI+PFNFQ09OREFSWURJQUdTLz48UFJPQ0VEVVJFUy8+PC9EUkdDTEFJTT48L0NGNT4=</OFFLINEDOCUMENT>
      </OFFLINEDOCUMENTS>
    </CLAIM>
  </eTRANSMITTAL>
</eCLAIMS>
